      - name: Deploy to Firebase (hosting + functions)
        env:
          KEY_FILE: ${{ runner.temp }}/gcloud-key.json
        run: |
          # write service account JSON to a temp file
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${KEY_FILE}"
          # activate service account for gcloud
          gcloud auth activate-service-account --key-file="${KEY_FILE}"
          # set project id (replace if different)
          gcloud config set project studio-5313059300-f1de0
          # ensure firebase-tools can use the application credentials
          export GOOGLE_APPLICATION_CREDENTIALS="${KEY_FILE}"
          # run firebase deploy
          firebase deploy --only hosting,functions --project studio-5313059300-f1de0
