name: Deploy to Firebase (Hosting + Functions)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud using service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies for functions (if any)
        run: |
          if [ -f functions/package.json ]; then
            echo "Installing functions dependencies..."
            cd functions
            npm install
            cd -
          else
            echo "No functions/package.json found - skipping dependency install."
          fi

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase (hosting + functions)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud-key.json
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${{ runner.temp }}/gcloud-key.json"
          firebase deploy --only hosting,functions --project studio-5313059300-f1de0
